name: isolate
version: 0.2.0
author: Dart Team <misc@dartlang.org>
description: Utility functions and classes related to the 'dart:isolate' library.
homepage: https://github.com/dart-lang/isolate
environment:
  sdk: '>=1.9.0-dev <2.0.0'
dev_dependencies:
  unittest: '>=0.10.0 <0.12.0'
